import { WorkspacePageGuide } from './WorkspacePageGuide';
import { useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { Link, NavLink, useLocation } from 'react-router-dom';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import { BusinessNavigation, BusinessFooter, unitPaths } from './BusinessNavigation';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import {LayoutDashboard,ClipboardList,FileText,Receipt,CreditCard,Files,Bell,LifeBuoy,UserRound,Settings,Factory,GraduationCap,CalendarDays,BookOpen,ScrollText,ArrowRight} from 'lucide-react';
const navIcons:Record<string,typeof LayoutDashboard>={dashboard:LayoutDashboard,requests:ClipboardList,quotes:FileText,invoices:Receipt,payments:CreditCard,files:Files,notifications:Bell,support:LifeBuoy,profile:UserRound,settings:Settings,production:Factory,courses:GraduationCap,sessions:CalendarDays,attendance:ClipboardList,resources:BookOpen,certificates:ScrollText,usage:Factory};
const navDescriptions:Record<string,string>={requests:'View and manage your submitted requests.',quotes:'Review quotations and responses.',invoices:'Issued invoices and amounts due.',payments:'Verified payments and instructions.',files:'Project files and private attachments.',notifications:'Important service updates.',support:'Open and follow support requests.',profile:'Your identity and contact details.',settings:'Account and security controls.',production:'Track active jobs and fulfilment.',usage:'Review recorded compute usage.',courses:'Browse courses and enrolment activity.',sessions:'Learning schedule and upcoming sessions.',attendance:'Your confirmed attendance records.',resources:'Learning resources and assignments.',certificates:'Completion certificates and verification.'};

type Unit = 'academy' | 'fabrication' | 'compute' | 'digital_business';
type RecordRow = Record<string, any>;
const shared = [['dashboard','Overview'],['requests','Requests'],['quotes','Quotes'],['invoices','Invoices'],['payments','Payments'],['files','Files'],['notifications','Notifications'],['support','Support'],['profile','Profile'],['settings','Account security']];
const specialist = {academy:[['courses','Courses & enrolment'],['sessions','Learning schedule'],['attendance','Attendance'],['resources','Resources & assignments'],['certificates','Certificates']],fabrication:[['production','Fabrication jobs']],compute:[['production','Compute jobs'],['usage','Usage history']],digital_business:[]};
const inputClass = 'mt-2 block w-full rounded-xl border p-3';
const money = (amount: unknown) => amount == null ? 'Awaiting quotation' : new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(Number(amount));
function Table({rows,columns,empty}:{rows:RecordRow[];columns:[string,string][];empty:string}) {
 return rows.length ? <div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-slate-100"><tr>{columns.map(([key,label])=><th className="p-3" key={key} scope="col">{label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t">{columns.map(([key])=><td key={key} className="p-3">{row[key] == null ? '—' : String(row[key]).replaceAll('_',' ')}</td>)}</tr>)}</tbody></table></div> : <p className="rounded-xl border bg-slate-50 p-5 text-sm text-muted">{empty}</p>;
}
export function BusinessPortal({unit}:{unit:Unit}) {
 const {user,profile,signOut}=useAuth();const location=useLocation();const base=unitPaths[unit];
 const page=location.pathname.slice(base.length+1)||'dashboard';const links=[...shared,...specialist[unit]];
 const [records,setRecords]=useState<Record<string,RecordRow[]>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[busy,setBusy]=useState(false);
 const accountScope=useRef('');accountScope.current=`${user?.id}:${unit}`;const uploadInput=useRef<HTMLInputElement>(null);
 const [orderId,setOrderId]=useState(''),[file,setFile]=useState<File|null>(null),[ticket,setTicket]=useState({subject:'',message:'',priority:'normal'});
 const load=useCallback(async()=>{
  if(!user||!supabase)return;
  const orders=await supabase.from('business_orders').select('*').eq('user_id',user.id).eq('unit_code',unit).order('created_at',{ascending:false});
  if(orders.error)throw orders.error;
  const ids=(orders.data||[]).map(x=>x.id);const data:Record<string,RecordRow[]>={orders:orders.data||[]};
  const queries:[string,PromiseLike<any>][]=[['notifications',supabase.from('business_notifications').select('*').eq('user_id',user.id).eq('unit_code',unit).order('created_at',{ascending:false})],['support',supabase.from('business_support_tickets').select('*').eq('user_id',user.id).eq('unit_code',unit).order('created_at',{ascending:false})]];
  if(ids.length)for(const table of ['business_quotes','business_invoices','business_files',...(unit==='fabrication'?['fabrication_jobs']:unit==='compute'?['compute_jobs','compute_usage_records']:[])])queries.push([table,supabase.from(table).select('*').in('order_id',ids).order('created_at',{ascending:false})]);
  const results=await Promise.all(queries.map(async([key,query])=>{const r=await query;if(r.error)throw r.error;return [key,r.data||[]] as const;}));
  for(const [key,rows] of results)data[key]=rows;
  const invoiceIds=(data.business_invoices||[]).map(x=>x.id);
  if(invoiceIds.length){const p=await supabase.from('business_payments').select('*').eq('user_id',user.id).in('invoice_id',invoiceIds);if(p.error)throw p.error;data.business_payments=p.data||[];const intents=await supabase.from('business_payment_intents').select('*').eq('user_id',user.id).in('invoice_id',invoiceIds);if(intents.error)throw intents.error;data.business_payment_intents=intents.data||[];}
  if(unit==='academy'){
   const [courses,enrollments]=await Promise.all([supabase.from('academy_courses').select('*').eq('is_active',true).order('title'),supabase.from('academy_enrollments').select('*').eq('user_id',user.id)]);
   if(courses.error||enrollments.error)throw courses.error||enrollments.error;data.courses=courses.data||[];data.enrollments=enrollments.data||[];
   const courseIds=data.enrollments.map(x=>x.course_id),enrollmentIds=data.enrollments.map(x=>x.id);
   if(courseIds.length)for(const table of ['academy_sessions','academy_resources']){const r=await supabase.from(table).select('*').in('course_id',courseIds);if(r.error)throw r.error;data[table]=r.data||[];}
   if(enrollmentIds.length)for(const table of ['academy_attendance','academy_certificates']){const r=await supabase.from(table).select('*').in('enrollment_id',enrollmentIds);if(r.error)throw r.error;data[table]=r.data||[];}
  }
  return data;
 },[user?.id,unit]);
 useEffect(()=>{let active=true;setRecords({});setError('');setNotice('');setLoading(true);setOrderId('');setFile(null);setSearch('');setTicket({subject:'',message:'',priority:'normal'});void load().then(data=>{if(active)setRecords(data||{});}).catch(e=>{if(active)setError(e.message||'Could not load this workspace.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[load]);
 async function action(work:()=>Promise<void>){if(busy)return;const scope=accountScope.current;setBusy(true);setError('');setNotice('');try{await work();const data=await load();if(scope===accountScope.current)setRecords(data||{});}catch(e){if(scope===accountScope.current)setError(e instanceof Error?e.message:'The action could not be completed.');}finally{if(scope===accountScope.current)setBusy(false);}}
 const rows=(key:string)=>(records[key]||[]).filter(x=>Object.values(x).some(value=>String(value??'').toLowerCase().includes(search.toLowerCase())));
 const orders=records.orders||[];const title=links.find(([key])=>key===page)?.[1]||'Workspace';
 const requestName=(id:string)=>orders.find(x=>x.id===id)?.order_number||id;
 async function upload(event:FormEvent){event.preventDefault();if(!file||!orderId||!user||!supabase)return;const selected=file;const allowed=/\.(stl|obj|step|stp|pdf|docx?|xlsx?|png|jpe?g|txt|csv|zip)$/i;if(!allowed.test(selected.name)||selected.size>20*1024*1024||selected.size===0){setError('Choose a supported, non-empty file up to 20 MB.');return;}
  await action(async()=>{if(!supabase)return;const path=`${user.id}/${orderId}/${crypto.randomUUID()}.${selected.name.split('.').pop()?.toLowerCase()}`;
   const stored=await supabase.storage.from('business-files').upload(path,selected,{upsert:false,contentType:selected.type||'application/octet-stream'});if(stored.error)throw stored.error;
   const saved=await supabase.from('business_files').insert({order_id:orderId,user_id:user.id,file_name:selected.name,file_url:path,storage_path:path,file_type:selected.type||'application/octet-stream'});
   if(saved.error){await supabase.storage.from('business-files').remove([path]);throw saved.error;}setFile(null);if(uploadInput.current)uploadInput.current.value='';setNotice('File uploaded privately and attached to your request.');});
 }
 async function download(row:RecordRow){await action(async()=>{if(!supabase||!row.storage_path)throw new Error('Contact support to retrieve this legacy file securely.');const r=await supabase.storage.from('business-files').createSignedUrl(row.storage_path,60);if(r.error)throw r.error;const link=document.createElement('a');link.href=r.data.signedUrl;link.target='_blank';link.rel='noopener noreferrer';link.click();});}
 let content:ReactNode;
 if(page==='dashboard')content=<><div className="grid gap-4 sm:grid-cols-3">{[['Requests',orders.length],['Invoices',(records.business_invoices||[]).length],['Unread notices',(records.notifications||[]).filter(x=>!x.read_at).length]].map(([label,value])=><Card key={String(label)}><p className="text-sm text-muted">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></Card>)}</div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{links.filter(([key])=>key!=='dashboard').map(([key,label])=>{const Icon=navIcons[key]||ArrowRight;return <Link key={key} to={base+'/'+key} className="group rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-royal-300 hover:shadow-md"><div className="flex items-start justify-between gap-4"><div className="grid h-12 w-12 place-items-center rounded-xl bg-slate-950 text-white"><Icon className="h-6 w-6"/></div><ArrowRight className="h-5 w-5 text-slate-400 transition group-hover:translate-x-1 group-hover:text-royal-600"/></div><h2 className="mt-5 text-lg font-black">{label}</h2><p className="mt-2 text-sm leading-6 text-muted">{navDescriptions[key]||'Open this workspace feature.'}</p><span className="mt-4 inline-flex rounded-lg bg-royal-600 px-3 py-2 text-xs font-bold text-white">Open {label}</span></Link>})}</section><Card><h2 className="mb-4 text-lg font-bold">Recent requests</h2><Table rows={orders.slice(0,5)} columns={ [['order_number','Request'],['title','Title'],['status','Status']]} empty="Your submitted requests will appear here."/><Link className="mt-5 inline-block text-royal-600 underline" to={base+'/request'}>Start a request</Link></Card></>;
 else if(page==='requests')content=<Table rows={rows('orders').map(x=>({...x,amount:money(x.amount)}))} columns={ [['order_number','Request'],['title','Title'],['quantity','Quantity'],['status','Status'],['amount','Quoted amount']]} empty="No requests match this view."/>;
 else if(page==='quotes'||page==='invoices')content=<><Table rows={rows(page==='quotes'?'business_quotes':'business_invoices').map(x=>({...x,request:requestName(x.order_id),amount:money(x.amount)}))} columns={[[page==='quotes'?'quote_number':'invoice_number',page==='quotes'?'Quote':'Invoice'],['request','Request'],['amount','Amount'],['status','Status'],[page==='quotes'?'valid_until':'due_at',page==='quotes'?'Valid until':'Due date']]} empty={`No ${page} have been issued for your requests.`}/>{page==='quotes'&&rows('business_quotes').filter(q=>q.status==='issued').map(q=><Card key={q.id}><p className="font-bold">Respond to {q.quote_number}</p><p className="mt-2 whitespace-pre-wrap text-sm">{q.notes}</p><div className="mt-3 flex flex-wrap gap-3">{[['accepted','Accept quote'],['revision_requested','Request revision'],['rejected','Decline quote']].map(([status,title])=><Button key={status} disabled={busy} onClick={()=>void action(async()=>{const r=await supabase!.from('business_quotes').update({status}).eq('id',q.id).eq('status','issued').select('id');if(r.error)throw r.error;if(!r.data?.length)throw new Error('This quote changed. Refresh before responding.');})}>{title}</Button>)}</div></Card>)}{page==='invoices'&&<><p className="text-sm text-muted">Only verified BillStack reconciliation marks an invoice paid. Transfer the exact amount displayed in your instruction.</p>{rows('business_invoices').filter(i=>['issued','awaiting_payment'].includes(i.status)&&Number(i.amount)>Number(i.amount_paid||0)).map(i=><Card key={i.id}><p className="font-bold">{i.invoice_number} · Outstanding {money(Number(i.amount)-Number(i.amount_paid||0))}</p><Button className="mt-3" disabled={busy} onClick={()=>void action(async()=>{const scope=accountScope.current;const r=await supabase!.functions.invoke('business-payment',{body:{invoice_id:i.id}});if(r.error)throw r.error;if(r.data?.error)throw new Error(r.data.message||r.data.error);const instruction=r.data?.data;if(!instruction?.bank?.account_number||!instruction?.intent?.amount)throw new Error('No verified payment instruction was returned.');if(scope===accountScope.current)setNotice(`Transfer exactly ${money(instruction.intent.amount)} to ${instruction.bank.bank_name}. Account: ${instruction.bank.account_number}. Name: ${instruction.bank.account_name}. Reference: ${instruction.intent.reference}. Payment updates after verification.`);})}>Get secure payment instruction</Button></Card>)}</>}</>;
 else if(page==='payments')content=<><Table rows={rows('business_payments').map(x=>({...x,amount:money(x.amount)}))} columns={ [['provider_reference','Payment reference'],['amount','Amount'],['status','Status'],['paid_at','Verified at']]} empty="No payment records for this platform."/><h2 className="text-lg font-bold">Payment instructions and reconciliation</h2><Table rows={rows('business_payment_intents').map(x=>({...x,amount:money(x.amount)}))} columns={[['reference','Reference'],['amount','Exact amount'],['status','Reconciliation status'],['paid_at','Verified at']]} empty="No transfer instructions have been created."/></>;
 else if(page==='files')content=<><Card><h2 className="text-lg font-bold">Attach request files</h2><p className="mt-2 text-sm text-muted">STL, OBJ, STEP, documents and images up to 20 MB. Files stay private to you and authorized service staff.</p><form onSubmit={e=>void upload(e)} className="mt-4 space-y-3"><label className="block">Request<select required className={inputClass} value={orderId} onChange={e=>setOrderId(e.target.value)}><option value="">Select a request awaiting review</option>{orders.filter(x=>['submitted','reviewing'].includes(x.status)).map(x=><option key={x.id} value={x.id}>{x.order_number} — {x.title}</option>)}</select></label><label className="block">File<input ref={uploadInput} required type="file" accept=".stl,.obj,.step,.stp,.pdf,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg,.txt,.csv,.zip" className={inputClass} onChange={e=>setFile(e.target.files?.[0]||null)}/></label><Button disabled={busy||!file}>{busy?'Uploading…':'Upload privately'}</Button></form></Card>{rows('business_files').map(x=><Card key={x.id}><p className="font-bold">{x.file_name}</p><p className="mt-1 text-sm text-muted">{requestName(x.order_id)}</p><Button className="mt-3" disabled={busy} onClick={()=>void download(x)}>Download securely</Button></Card>)}</>;
 else if(page==='notifications')content=rows('notifications').length?rows('notifications').map(x=><Card key={x.id}><h2 className="font-bold">{x.title}</h2><p className="mt-2">{x.body}</p>{!x.read_at&&<Button className="mt-3" disabled={busy} onClick={()=>void action(async()=>{const r=await supabase!.from('business_notifications').update({read_at:new Date().toISOString()}).eq('id',x.id).eq('user_id',user!.id);if(r.error)throw r.error;})}>Mark read</Button>}</Card>):<p>No notifications for this platform.</p>;
 else if(page==='support')content=<><Card><h2 className="font-bold">Open a support ticket</h2><form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();void action(async()=>{const r=await supabase!.from('business_support_tickets').insert({user_id:user!.id,unit_code:unit,...ticket,status:'open'});if(r.error)throw r.error;setTicket({subject:'',message:'',priority:'normal'});setNotice('Support ticket submitted.');});}}><label className="block">Subject<input required minLength={3} maxLength={180} className={inputClass} value={ticket.subject} onChange={e=>setTicket({...ticket,subject:e.target.value})}/></label><label className="block">Message<textarea required minLength={10} maxLength={10000} className={inputClass} value={ticket.message} onChange={e=>setTicket({...ticket,message:e.target.value})}/></label><label className="block">Priority<select className={inputClass} value={ticket.priority} onChange={e=>setTicket({...ticket,priority:e.target.value})}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><Button disabled={busy}>Submit ticket</Button></form></Card>{rows('support').map(x=><Card key={x.id}><div className="flex justify-between gap-4"><h2 className="font-bold">{x.subject}</h2><span>{x.status}</span></div><p className="mt-2 whitespace-pre-wrap">{x.message}</p>{x.admin_response&&<p className="mt-3 rounded-lg bg-blue-50 p-3">IHLink response: {x.admin_response}</p>}</Card>)}</>;
 else if(page==='profile')content=<Card><dl className="space-y-4"><div><dt className="text-sm text-muted">Name</dt><dd>{[profile?.first_name,profile?.last_name].filter(Boolean).join(' ')||'Not provided'}</dd></div><div><dt className="text-sm text-muted">Email</dt><dd>{user?.email}</dd></div><div><dt className="text-sm text-muted">Phone</dt><dd>{profile?.phone||'Not provided'}</dd></div><div><dt className="text-sm text-muted">Account status</dt><dd>{profile?.status}</dd></div></dl></Card>;
 else if(page==='settings')content=<Card><h2 className="font-bold">Account security</h2><p className="mt-2 text-sm text-muted">Reset your password through the verified email flow.</p><Link className="mt-4 inline-block text-royal-600 underline" to="/reset-password">Reset password</Link><div className="mt-5"><Button onClick={()=>void signOut()}>Sign out</Button></div></Card>;
 else if(page==='production')content=<Table rows={rows(unit==='fabrication'?'fabrication_jobs':'compute_jobs').map(x=>({...x,request:requestName(x.order_id)}))} columns={unit==='fabrication'?[['request','Request'],['process','Process'],['material','Material'],['dimensions','Dimensions'],['status','Production status']]:[['request','Request'],['workload_type','Workload'],['compute_profile','Requested profile'],['estimated_hours','Estimated hours'],['status','Job status']]} empty="Your reviewed specialist jobs will appear here."/>;
 else if(page==='usage')content=<><Table rows={rows('compute_usage_records').map(x=>({...x,request:requestName(x.order_id)}))} columns={ [['request','Request'],['started_at','Started'],['ended_at','Ended'],['hours','Recorded hours'],['credits_used','Credits used']]} empty="No verified compute usage has been recorded."/><p className="text-sm text-muted">Hardware availability and pricing are confirmed during review. A request does not reserve an uncommissioned machine.</p></>;
 else if(page==='courses')content=(records.courses||[]).length?rows('courses').map(c=>{const enrollment=(records.enrollments||[]).find(e=>e.course_id===c.id);return <Card key={c.id}><p className="text-xs text-muted">{c.category} · {c.delivery_mode||'Mode to be confirmed'}</p><h2 className="mt-1 text-xl font-bold">{c.title}</h2><p className="mt-2">{c.description}</p><p className="mt-2 text-sm">{c.duration_text} · {Number(c.fee)>0?money(c.fee):'Fee to be confirmed'}</p>{enrollment?<p className="mt-3 font-semibold">Application: {enrollment.status} · Progress: {enrollment.progress}%</p>:<Button className="mt-4" disabled={busy} onClick={()=>void action(async()=>{const r=await supabase!.rpc('apply_academy_course',{target_course:c.id});if(r.error)throw r.error;setNotice('Application submitted for Academy review.');})}>Apply for this course</Button>}</Card>;}):<p>Courses will appear after their schedules and details are approved. Contact Academy to discuss your learning goals.</p>;
 else if(page==='sessions')content=<Table rows={rows('academy_sessions')} columns={ [['title','Session'],['starts_at','Starts'],['ends_at','Ends'],['venue','Venue'],['status','Status']]} empty="No sessions are scheduled for your enrolled courses."/>;
 else if(page==='attendance')content=<Table rows={rows('academy_attendance').map(x=>({...x,session:(records.academy_sessions||[]).find(s=>s.id===x.session_id)?.title||'Session'}))} columns={ [['session','Session'],['status','Attendance'],['recorded_at','Recorded']]} empty="No attendance records have been confirmed."/>;
 else if(page==='resources')content=rows('academy_resources').length?rows('academy_resources').map(x=><Card key={x.id}><h2 className="font-bold">{x.title}</h2><p className="mt-2 text-sm">{x.resource_type}{x.due_at?' · Due '+new Date(x.due_at).toLocaleString():''}</p>{/^https:\/\//.test(x.resource_url)&&<a className="mt-3 inline-block text-royal-600 underline" href={x.resource_url} target="_blank" rel="noopener noreferrer">Open learning material</a>}</Card>):<p>No learning materials have been published for your active enrolments.</p>;
 else if(page==='certificates')content=rows('academy_certificates').length?rows('academy_certificates').map(x=><Card key={x.id}><h2 className="font-bold">Course completion certificate</h2><p className="mt-2">{x.certificate_code}</p><p className="mt-2 text-sm">Issued {new Date(x.issued_at).toLocaleDateString()} · {x.status}</p><Link className="mt-4 inline-block text-royal-600 underline" to={base+'/verify-certificate?code='+x.certificate_code}>Verify certificate</Link></Card>):<p>Certificates are issued after authorized staff confirm completion.</p>;
 else content=<p>This workspace page is unavailable.</p>;
 return <><BusinessNavigation unit={unit}/><div className="mx-auto grid max-w-[1400px] gap-6 px-5 py-8 lg:grid-cols-[240px_minmax(0,1fr)]"><aside className="min-w-0 print:hidden"><nav aria-label="Workspace features" className="flex min-w-0 flex-wrap gap-2 overflow-hidden rounded-2xl border bg-white p-3 shadow-sm lg:sticky lg:top-5 lg:w-full lg:flex-col">{links.map(([key,label])=><NavLink key={key} to={base+'/'+key} className={({isActive})=>'flex min-w-0 max-w-full items-center overflow-hidden rounded-xl px-3 py-2.5 text-sm font-semibold transition lg:w-full '+(isActive?'bg-royal-600 text-white shadow-sm':'text-slate-700 hover:bg-slate-100 hover:text-royal-700')}><span className="block min-w-0 flex-1 truncate">{label}</span></NavLink>)}</nav></aside><main className="min-w-0"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><h1 className="text-3xl font-black">{title}</h1><Button variant="secondary" className="print:hidden" onClick={()=>window.print()}>Print / save PDF</Button></div><WorkspacePageGuide unit={unit} page={page} base={base}/>{!['dashboard','profile','settings'].includes(page)&&<label className="mb-5 block text-sm font-bold text-slate-700 print:hidden">Search this page<input type="search" placeholder="Search this workspace…" className={inputClass} value={search} onChange={e=>setSearch(e.target.value)}/></label>}{error&&<p role="alert" className="mb-5 rounded-xl bg-rose-50 p-4 text-rose-700">{error}</p>}{notice&&<p role="status" className="mb-5 rounded-xl bg-emerald-50 p-4">{notice}</p>}<div className="space-y-5">{loading?<p role="status">Loading your platform records…</p>:error&&!Object.keys(records).length?<Button onClick={()=>void action(async()=>{})}>Retry loading</Button>:content}</div></main></div><BusinessFooter unit={unit}/></>;
}

export function AcademyCertificateVerification(){const location=useLocation();const [code,setCode]=useState(new URLSearchParams(location.search).get('code')||''),[result,setResult]=useState<RecordRow|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function verify(e:FormEvent){e.preventDefault();setResult(null);setMessage('');if(!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(code.trim())){setMessage('Enter the full certificate verification code.');return;}if(!supabase)return;setBusy(true);const r=await supabase.from('academy_certificate_registry').select('certificate_code,course_title,issued_at,status').eq('certificate_code',code.trim()).maybeSingle();setBusy(false);if(r.error)setMessage('Verification is unavailable. Please try again.');else if(!r.data)setMessage('No issued certificate matches this code.');else setResult(r.data);}
 return <><BusinessNavigation unit="academy"/><main className="mx-auto max-w-2xl px-6 py-14"><h1 className="text-3xl font-black">Verify an Academy certificate</h1><p className="mt-4 text-muted">Confirm the course, issue date and current validity using the certificate code.</p><form className="mt-6 space-y-4" onSubmit={e=>void verify(e)}><label className="block">Verification code<input required className={inputClass} value={code} onChange={e=>setCode(e.target.value)}/></label><Button disabled={busy}>{busy?'Verifying…':'Verify certificate'}</Button></form>{message&&<p role="status" className="mt-5">{message}</p>}{result&&<Card className="mt-6"><h2 className="text-xl font-bold">{result.course_title}</h2><p className="mt-3">Status: {result.status}</p><p className="mt-2">Issued: {new Date(result.issued_at).toLocaleDateString()}</p><p className="mt-2 text-sm">Code: {result.certificate_code}</p></Card>}</main><BusinessFooter unit="academy"/></>;
}
