import { Link } from 'react-router-dom';

type Unit = 'academy' | 'fabrication' | 'compute' | 'digital_business';
type Guide = { title: string; body: string; steps: string[]; next: string; label: string };
const guides: Record<string, Guide> = {
 requests: {title:'Prepare a request that can be reviewed',body:'Your request records the scope to be quoted. Include the required result, quantity, deadline and any constraints before the team reviews it.',steps:['Attach supporting files to the matching request.', 'Review the issued quote before accepting its scope.', 'Track changes here using the request number.'],next:'files',label:'Attach request files'},
 quotes: {title:'Review scope before accepting a quote',body:'Check the quoted amount, validity date, deliverables and notes against your request. Acceptance confirms the quoted scope; it does not mark an invoice paid.',steps:['Ask for a revision if a specification or deliverable is missing.', 'Accept only the current quote you intend to proceed with.', 'Review the resulting invoice and outstanding amount.'],next:'invoices',label:'Review invoices'},
 invoices: {title:'Use the invoice as your payment reference',body:'An invoice belongs to a specific request. Review its outstanding amount and current status before opening the bank transfer payment page.',steps:['Open the payment page for the selected invoice and choose one of the two company bank accounts.', 'Use the exact displayed transfer amount and reference.', 'Upload your transfer receipt; Finance verifies the bank statement before marking the invoice paid.'],next:'payments',label:'Check reconciliation status'},
 payments: {title:'Understand payment and reconciliation status',body:'This page shows payment records and transfer instructions for this platform. An invoice remains unpaid until Finance verifies your receipt against the bank statement.',steps:['Match the reference to the invoice you intended to pay.', 'Upload proof of the exact outstanding amount and check the Finance verification status.', 'If a transfer is missing, send its reference through support; do not submit bank credentials.'],next:'support',label:'Report a payment issue'},
 files: {title:'Keep files attached to the right request',body:'Files are stored privately for your request and authorized service staff. Use clear filenames and the latest revision so the team can identify the intended version.',steps:['Select the request that is awaiting review.', 'Upload a supported, non-empty file of at most 20 MB.', 'Explain any replacement or revision through support.'],next:'requests',label:'Review your requests'},
 production: {title:'Follow the specialist job linked to your request',body:'Job records describe the reviewed workload or fabrication specification and its current status. Submitting a request alone does not confirm capacity, production or completion.',steps:['Check that the job specification matches the accepted scope.', 'Use the request number when asking about changes.', 'Review completion and delivered results with the team.'],next:'support',label:'Ask about a job'},
 usage: {title:'Review recorded compute consumption',body:'Usage records identify the request, recorded session times, hours and credits. Hardware availability and charging terms must be confirmed in the reviewed scope.',steps:['Compare recorded hours with the agreed work.', 'Check the matching invoice for approved charges.', 'Report missing or disputed entries before approving further work.'],next:'invoices',label:'Review compute invoices'},
 courses: {title:'Choose an approved learning programme',body:'Only active courses configured by Academy appear in this catalogue. Review the delivery mode, duration, course description and fee before applying.',steps:['Apply to the course that matches your learning goals.', 'Track the application until Academy confirms enrolment.', 'After enrolment, check your schedule and published learning materials.'],next:'support',label:'Discuss a learning programme'},
 sessions: {title:'Plan around your enrolled course schedule',body:'The schedule shows sessions published for your enrolled courses, including their start and end times, venue and status.',steps:['Confirm the venue or delivery arrangement before attending.', 'Check for schedule changes before each session.', 'Contact Academy if an expected session is missing.'],next:'attendance',label:'Review attendance'},
 attendance: {title:'Check your confirmed attendance records',body:'Attendance is recorded by authorized Academy staff for scheduled sessions. These records help you and your instructor identify missed learning activities.',steps:['Match each entry to the session you attended.', 'Report an incorrect entry with the session date.', 'Discuss make-up work with Academy where needed.'],next:'support',label:'Request an attendance review'},
 resources: {title:'Use the materials published for your courses',body:'Learning resources and assignment links are published for enrolled courses. Check the resource type and any displayed due date before opening the material.',steps:['Open the published material using its secure link.', 'Follow the submission instructions in the assignment.', 'Ask Academy if a resource or submission route is missing.'],next:'support',label:'Ask about learning materials'},
 certificates: {title:'Verify confirmed course completion',body:'Certificates appear after authorized Academy staff confirm completion. Each issued certificate has a verification code and a current validity status.',steps:['Check the issue date and certificate status.', 'Use the verification link to confirm the course and validity.', 'Contact Academy if a completed course has no certificate.'],next:'support',label:'Ask about a certificate'},
 notifications: {title:'Keep track of updates for this service',body:'Notifications relate to your requests and activity on this platform. Open the relevant request or invoice when an update requires action.',steps:['Review new notices before marking them read.', 'Use the matching request number to follow up.', 'Contact support if an update is unclear.'],next:'requests',label:'Open your requests'},
 support: {title:'Give support the details needed to help',body:'Describe the issue and include its request, invoice or payment reference where applicable. Your ticket and staff response stay within this service workspace.',steps:['Choose a clear subject and explain what happened.', 'Include the expected result and relevant reference.', 'Keep passwords, one-time codes and full card details out of the message.'],next:'requests',label:'Find a request reference'},
};
const unitNames: Record<Unit,string> = {academy:'Academy',fabrication:'Fabrication',compute:'AI & Compute',digital_business:'Digital Business'};
export function WorkspacePageGuide({unit,page,base}:{unit:Unit;page:string;base:string}) {
 const guide=guides[page];
 if(!guide)return null;
 return <section aria-label={`${unitNames[unit]} ${page} guidance`} className="mb-6 rounded-2xl border border-blue-100 bg-blue-50/50 p-5 print:hidden"><p className="text-xs font-semibold uppercase tracking-wide text-blue-700">{unitNames[unit]} · {page.replaceAll('_',' ')}</p><h2 className="mt-2 text-lg font-bold">{guide.title}</h2><p className="mt-2 max-w-4xl text-sm leading-relaxed text-slate-700">{guide.body}</p><ol className="mt-3 list-decimal space-y-1 pl-5 text-sm text-slate-700">{guide.steps.map(step=><li key={step}>{step}</li>)}</ol><Link className="mt-4 inline-block text-sm font-semibold text-blue-700 underline" to={`${base}/${guide.next}`}>{guide.label}</Link></section>;
}
